server:
  port: 10001
spring:
  application:
    name: admin-client
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.99.196.27:33306/springboot
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  redis: # 配置redis
      host: 47.99.196.27
      port: 6379

  boot:
    admin:
      client:
        url: http://localhost:8769   # 指定注册地址 , Spring Boot Admin Server地址
mybatis:
  type-aliases-package: com.wu.pojo




management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS